// Base
using System;
using System.Collections.Generic;

// Unity
using UnityEngine;
using UnityEngine.Tilemaps;

// Sub-namespace for tilemap-related utilities.
namespace PCG.Tilemaps
{
    /// <summary>
    /// Manages data related to the tilemaps in the simulation.
    /// </summary>
    public class TilemapSystem : ManagerSystem
    {
        // Data structure holding data related to the tilemaps, and tiles, which is accessed by other systems.
        public TilemapData tilemapData;
        // Store the highest engagement room generated so far...
        public RoomData highestEngagementRoom;

        [Header("All Tilemaps")]
        public List<Tilemap> tilemaps;

        [Header("Decoration Tilemap")]
        public Tilemap tilemap;
        [Space]
        [Header("Collidable Tilemap")]
        [Tooltip("Tilemap Contains Rigidbody, Composite collider, tilemap collider (NOT TRIGGERS)")]
        public Tilemap collidable;
        [Space]
        [Header("Trigger Tilemap")]
        [Tooltip("Tilemap Contains Rigidbody, Composite collider, tilemap collider (TRIGGERS)")]
        public Tilemap entities;

        // Empty GameObject for tiles GameObjects generated to be parented to.
        public Transform instantiatedTilesParent;

        protected void Awake()
        {
            // Initialise tilemap data references
            tilemapData.floor = tilemap;
            tilemapData.collidable = collidable;
            tilemapData.trigger = entities;
        }

        /// <summary>
        /// Add the tilemaps to the list whenever we change the tilemap System in Editor.
        /// </summary>
        private void OnValidate()
        {
            AddTilemapToList(tilemap);
            AddTilemapToList(collidable);
            AddTilemapToList(entities);

            // Initialise tilemap data references
            tilemapData.floor = tilemap;
            tilemapData.collidable = collidable;
            tilemapData.trigger = entities;
        }

        /// <summary>
        /// Adds the tilemap to the list of <c>tilemaps</c> if not already.
        /// </summary>
        /// <param name="tilemapToAdd">Tilemap to be added to list.</param>
        private void AddTilemapToList(Tilemap tilemapToAdd)
        {
            if (tilemapToAdd != null && !tilemaps.Contains(tilemapToAdd))
            {
                tilemaps.Add(tilemapToAdd);
            }
        }

        /// <summary>
        /// Reset the <c>TilemapSystem</c>.
        /// </summary>
        public override void ResetSystem() { }
    }

    /// <summary>
    /// Data container for tilemap related data, including list of tiles for PCG, and tilemaps of simulation.
    /// </summary>
    [Serializable]
    public class TilemapData
    {
        /*[HideInInspector]*/ public List<Tilemap> allTilemaps = new();

        /*[HideInInspector]*/ public Tilemap floor = new();
        /*[HideInInspector]*/ public Tilemap collidable = new();
        /*[HideInInspector]*/ public Tilemap trigger = new();

        public List<Tile> tiles = new();

        public TilemapData()
        {
            allTilemaps.AddRange(new List<Tilemap>
            {
                floor,
                collidable,
                trigger
            });
        }
    }

    /// <summary>
    /// Data container for data of room generated by PCG system in the simulation.
    /// </summary>
    [Serializable]
    public struct RoomData
    {
        public Tile[,] tilemap;

        [HideInInspector] public int RoomWidth;
        [HideInInspector] public int RoomHeight;
        [HideInInspector] public EngagementMetrics engagementPreviousRoom;

        public (int x, int y) RoomCentre;

        public (int x, int y) TopDoor;
        public (int x, int y) BottomDoor;
        public (int x, int y) LeftDoor;
        public (int x, int y) RightDoor;

        /// <summary>
        /// Generates a RoomData instance with specified width and height.
        /// </summary>
        /// <param name="width">Width of the room.</param>
        /// <param name="height">Height of the room.</param>
        /// <returns>RoomData instance with centre and door positions.</returns>
        public static RoomData GenerateRoom(int width, int height)
        {
            RoomData roomData = new RoomData
            {
                RoomWidth = width,
                RoomHeight = height,
                RoomCentre = (width / 2, height / 2),
                TopDoor = (width / 2, height - 1),
                BottomDoor = (width / 2, 0),
                LeftDoor = (0, height / 2),
                RightDoor = (width - 1, height / 2)
            };

            return roomData;
        }
    }

    /// <summary>
    /// Data container for an agents engagement with a room. Engagement is measured in the number of
    /// items picked up and the amount of exploring the agent did. Internally tracks these along with agents reward in
    /// this episode.
    /// </summary>
    [Serializable]
    public struct EngagementMetrics
    {
        public float EngagementScore => itemPickups + exploration;
        public int itemPickups;
        public float exploration;

        public float RewardScore;

        /// <summary>
        /// Generate a new EngagementMetrics with parameters.
        /// </summary>
        /// <param name="items">itemPickups</param>
        /// <param name="exploring">exploration</param>
        /// <param name="reward">RewardScore</param>
        public EngagementMetrics(int items, float exploring, float reward)
        {
            itemPickups = items;
            exploration = exploring;
            RewardScore = reward;
        }

        /// <summary>
        /// Reset the engagement data stored to default.
        /// </summary>
        public void ResetEngagement()
        {
            RewardScore = default;
            itemPickups = default;
            exploration = default;
        }

        /// <summary>
        /// Set reward value to reward engagement metric.
        /// </summary>
        /// <param name="reward">Reward value to set.</param>
        public void SetRewardScore(float reward) => RewardScore = reward;
        /// <summary>
        /// Add reward value to reward engagement metric.
        /// </summary>
        /// <param name="reward">Reward value to add.</param>
        public void AddRewardScore(float reward) => RewardScore += reward;

        /// <summary>
        /// Add item value to item pickup engagement metric.
        /// </summary>
        /// <param name="item">Item value to add.</param>
        public void AddItemPickup(int item) => itemPickups += item;
        /// <summary>
        /// Add exploration value to exploration engagement metric.
        /// </summary>
        /// <param name="explore">Exploring value to add.</param>
        public void AddExploration(float explore) => exploration += explore;
    }
}